name: Release Build

on:
  release:
    types: [published]

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
