name: Tag Staging

on:
  push:
    branches:
      - 'staging'

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        # uses: mathieudutour/github-tag-action@v4.5
        uses: anothrNick/github-tag-action@1.17.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: 'staging'
          DRY_RUN: true
