name: Stg Build Deploy Payer API

on:
  push:
    tags:
      - '*'

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:

      - name: checkout staging
        uses: actions/checkout@v2.0.0
        with:
          ref: 'staging'

      - name: get staging sha
        id: staging
        run: |
          echo "STAGING HEAD: $(git rev-parse HEAD)"
          echo "::set-env name=STAGING_SHA::$(git rev-parse HEAD)"

      - name: checkout tag
        uses: actions/checkout@v2.0.0

      - name: Validate staging is at tag
        env:
          SHA: ${{ github.sha }}
          STAGING_SHA: ${{ env.STAGING_SHA }}
        run: |
          echo "sha: $SHA staging_head: $STAGING_SHA"
          if [ $SHA == $STAGING_SHA ]; then exit 0 ; else exit 1 ; fi

      # - name: Check git tag
      #   run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"

      # - name: Get staging commit sha
      #   run: echo "::set-env name=STAGING_SHA::$(git rev-parse origin/staging)"

      # - name: Set to skip if no git tag
      #   if: ${{ env.HEAD_TAG == '' }}
      #   run: |
      #     echo "$HEAD_TAG fail step because head of branch is not a tag"
      #     echo "::set-output name=RUN_JOBS::false"
      # - name: Set to continue if tag exists
      #   if: ${{ env.HEAD_TAG != '' }}
      #   run: |
      #     echo "$HEAD_TAG continue processing"
      #     echo "::set-output name=RUN_JOBS::true"
  # build:
  #   runs-on: ubuntu-latest
  #   needs: [build-check]
  #   steps:
  #     - name: run the build
  #       run: echo "build ran because tag found"
