name: Stg Build Deploy Payer API

on:
  push:
    branches:
      - 'staging'
    tags:
      - '*'

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Check git tag
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"

      - name: Set to skip if no git tag
        if: ${{ env.HEAD_TAG == '' }}
        run: |
          echo "$HEAD_TAG fail step because head of branch is not a tag"
          echo "::set-output name=RUN_JOBS::false"
      - name: Set to continue if tag exists
        if: ${{ env.HEAD_TAG != '' }}
        run: |
          echo "$HEAD_TAG continue processing"
          echo "::set-output name=RUN_JOBS::true"
  build:
    runs-on: ubuntu-latest
    if: ${{ core.getInput('RUN_JOBS') == 'true' }}
    # needs: [build-check]
    steps:
      - name: run the build
        run: echo "build ran because tag found"
