name: Test pull_request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Check if Git tag exists
        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"

      - name: Runs only if Git tag exists
        run: echo"This runs because Git tag points at HEAD ..."
        if: env.HEAD_TAG != ''
